// NOTE: This file was generated by the ServiceGenerator.

// ----------------------------------------------------------------------------
// API:
//   players/v2
// Description:
//   API for NFL Players

#import "GTLRPlayersQuery.h"

#import "GTLRPlayersObjects.h"

@implementation GTLRPlayersQuery

@dynamic fields;

@end

@implementation GTLRPlayersQuery_PlayerInsert

+ (instancetype)queryWithObject:(GTLRPlayers_MainAPIPlayer *)object {
  if (object == nil) {
    GTLR_DEBUG_ASSERT(object != nil, @"Got a nil object");
    return nil;
  }
  NSString *pathURITemplate = @"player";
  GTLRPlayersQuery_PlayerInsert *query =
    [[self alloc] initWithPathURITemplate:pathURITemplate
                               HTTPMethod:@"POST"
                       pathParameterNames:nil];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLRPlayers_MainAPIPlayer class];
  query.loggingName = @"players.player.insert";
  return query;
}

@end

@implementation GTLRPlayersQuery_PlayerList

+ (instancetype)query {
  NSString *pathURITemplate = @"players";
  GTLRPlayersQuery_PlayerList *query =
    [[self alloc] initWithPathURITemplate:pathURITemplate
                               HTTPMethod:nil
                       pathParameterNames:nil];
  query.expectedObjectClass = [GTLRPlayers_MainAPIPlayerList class];
  query.loggingName = @"players.player.list";
  return query;
}

@end
