// NOTE: This file was generated by the ServiceGenerator.

// ----------------------------------------------------------------------------
// API:
//   players/v2
// Description:
//   API for NFL Players

#import "GTLRPlayersObjects.h"

// ----------------------------------------------------------------------------
//
//   GTLRPlayers_MainAPIPlayer
//

@implementation GTLRPlayers_MainAPIPlayer
@dynamic name, position;
@end


// ----------------------------------------------------------------------------
//
//   GTLRPlayers_MainAPIPlayerList
//

@implementation GTLRPlayers_MainAPIPlayerList
@dynamic players;

+ (NSDictionary<NSString *, Class> *)arrayPropertyToClassMap {
  NSDictionary<NSString *, Class> *map = @{
    @"players" : [GTLRPlayers_MainAPIPlayer class]
  };
  return map;
}

@end
