// NOTE: This file was generated by the ServiceGenerator.

// ----------------------------------------------------------------------------
// API:
//   players/v2
// Description:
//   API for NFL Players

#if GTLR_BUILT_AS_FRAMEWORK
  #import "GTLR/GTLRQuery.h"
#else
  #import "GTLRQuery.h"
#endif

#if GTLR_RUNTIME_VERSION != 3000
#error This file was generated by a different version of ServiceGenerator which is incompatible with this GTLR library source.
#endif

@class GTLRPlayers_MainAPIPlayer;

NS_ASSUME_NONNULL_BEGIN

/**
 *  Parent class for other Players query classes.
 */
@interface GTLRPlayersQuery : GTLRQuery

/** Selector specifying which fields to include in a partial response. */
@property(nonatomic, copy, nullable) NSString *fields;

@end

/**
 *  GTLRPlayersQuery_PlayerInsert
 *
 *  Method: players.player.insert
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopePlayersUserinfoEmail
 */
@interface GTLRPlayersQuery_PlayerInsert : GTLRPlayersQuery
// Previous library name was
//   +[GTLQueryPlayers queryForPlayerInsertWithObject:]

/**
 *  Fetches a @c GTLRPlayers_MainAPIPlayer.
 *
 *  @param object The @c GTLRPlayers_MainAPIPlayer to include in the query.
 *
 *  @returns GTLRPlayersQuery_PlayerInsert
 */
+ (instancetype)queryWithObject:(GTLRPlayers_MainAPIPlayer *)object;

@end

/**
 *  GTLRPlayersQuery_PlayerList
 *
 *  Method: players.player.list
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopePlayersUserinfoEmail
 */
@interface GTLRPlayersQuery_PlayerList : GTLRPlayersQuery
// Previous library name was
//   +[GTLQueryPlayers queryForPlayerList]

/**
 *  Fetches a @c GTLRPlayers_MainAPIPlayerList.
 *
 *  @returns GTLRPlayersQuery_PlayerList
 */
+ (instancetype)query;

@end

NS_ASSUME_NONNULL_END
